### ISSUE TITLE
building gqrx on OSX Sierra on HomeBrew : gnuradio-audio development package not found

### ISSUE THREAD

**Issue by martinbogo** [daveio/homebrew-sdrtools#2]
Sage:~ martinb$ brew install --build-from-source --HEAD gqrx
==> Installing gqrx from daveio/sdrtools
==> Cloning https://github.com/csete/gqrx.git
Updating /Users/martinb/Library/Caches/Homebrew/gqrx--git
==> Checking out revision 6c81b3c9f2fbda185481fa0213de04bfcf4de584
==> Patching
patching file gqrx.pro
Hunk #1 succeeded at 25 (offset 1 line).
Hunk #2 succeeded at 264 (offset 28 lines).
==> export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig; qmake -set PKG_CONFIG /usr/local/bin/pkg-config
==> export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig; qmake -query
==> export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig; qmake gqrx.pro
Last 15 lines from /Users/martinb/Library/Logs/Homebrew/gqrx/03.pkgconfig;:
2017-04-16 14:00:59 -0500

export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig; qmake gqrx.pro

Info: creating stash file /private/tmp/gqrx-20170416-77829-1kri9wr/.qmake.stash
Project MESSAGE: No prefix given. Using /usr/local
Project MESSAGE: Gqrx configured with gnuradio-audio backend.
Project ERROR: gnuradio-audio development package not found

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/daveio/homebrew-sdrtools/issues

**Comment by niftylettuce** [comment]
same issue

**Comment by Almeritek** [comment]
same issue too :(

**Comment by daveio** [comment]
@martinbogo @niftylettuce @Almeritek Thanks for the report. It's been ages since I touched this tap, and I think the best thing to do is to use the far superior @pothosware and @dholm taps.

```
brew untap daveio/homebrew-sdrtools
brew tap pothosware/homebrew-pothos
brew tap dholm/homebrew-sdr
```
