### ISSUE TITLE
formula.factory is deprecated

### ISSUE THREAD

**Issue by s3cj0y** [daveio/homebrew-sdrtools#5]
Warning: Calling Formula.factory is deprecated!
Use Formulary.factory instead.

**Comment by daveio** [comment]
@s3cj0y Thanks for the report. It's been ages since I touched this tap, and I think the best thing to do is to use the far superior @pothosware and @dholm taps.

```
brew untap daveio/homebrew-sdrtools
brew tap pothosware/homebrew-pothos
brew tap dholm/homebrew-sdr
```
