### ISSUE TITLE
build problems

### ISSUE THREAD

**Issue by pquodling** [daveio/homebrew-sdrtools#6]
➜  ~ brew tap daveio/sdrtools
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (caskroom/cask).
No changes to formulae.

==> Tapping daveio/sdrtools
Cloning into '/usr/local/Homebrew/Library/Taps/daveio/homebrew-sdrtools'...
remote: Counting objects: 9, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 9 (delta 0), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (9/9), done.
Warning: Calling 'depends_on :python' is deprecated!
Use 'depends_on "python"' instead.
/usr/local/Homebrew/Library/Taps/daveio/homebrew-sdrtools/gnuradio.rb:13:in `<class:Gnuradio>'
Please report this to the daveio/sdrtools tap!

Warning: Calling 'depends_on ... => :python' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/daveio/homebrew-sdrtools/gnuradio.rb:15:in `<class:Gnuradio>'
Please report this to the daveio/sdrtools tap!

Warning: Calling 'depends_on ... => :python' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/daveio/homebrew-sdrtools/gnuradio.rb:16:in `<class:Gnuradio>'
Please report this to the daveio/sdrtools tap!

Warning: Calling 'depends_on ... => :python' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/daveio/homebrew-sdrtools/gnuradio.rb:17:in `<class:Gnuradio>'
Please report this to the daveio/sdrtools tap!

Warning: Calling 'depends_on ... => :python' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/daveio/homebrew-sdrtools/gnuradio.rb:18:in `<class:Gnuradio>'
Please report this to the daveio/sdrtools tap!

Warning: Calling 'depends_on ... => :python' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/daveio/homebrew-sdrtools/gnuradio.rb:19:in `<class:Gnuradio>'
Please report this to the daveio/sdrtools tap!

Warning: Calling 'depends_on ... => :python' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/daveio/homebrew-sdrtools/gnuradio.rb:20:in `<class:Gnuradio>'
Please report this to the daveio/sdrtools tap!

Warning: Calling 'depends_on :fortran' is deprecated!
Use 'depends_on "gcc"' instead.
/usr/local/Homebrew/Library/Taps/daveio/homebrew-sdrtools/gnuradio.rb:21:in `<class:Gnuradio>'
Please report this to the daveio/sdrtools tap!

Warning: Calling 'depends_on ... => :python' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/daveio/homebrew-sdrtools/gnuradio.rb:37:in `<class:Gnuradio>'
Please report this to the daveio/sdrtools tap!

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/daveio/homebrew-sdrtools/rtlsdr.rb
Calling MacOS.xcode_version is disabled!
Use MacOS::Xcode.version instead.
/usr/local/Homebrew/Library/Taps/daveio/homebrew-sdrtools/rtlsdr.rb:15:in `<class:Rtlsdr>'
Please report this to the daveio/sdrtools tap!
Or, even better, submit a PR to fix it!
Error: Cannot tap daveio/sdrtools: invalid syntax in tap!
➜  ~

**Comment by daveio** [comment]
@pquodling Thanks for the report. It's been ages since I touched this tap, and I think the best thing to do is to use the far superior @pothosware and @dholm taps.

```
brew untap daveio/homebrew-sdrtools
brew tap pothosware/homebrew-pothos
brew tap dholm/homebrew-sdr
```
